### ISSUE TITLE
VEP help

### ISSUE THREAD

**Issue by sonoro1234** [kaoskorobase/skUG#1]
recently found a recomendation of VEPconvolution plugin
would like to get some info but cant find help file

best
victor

**Comment by kaoskorobase** [comment]
Hi Victor, I haven't used that UGen in a long time. You should probably check out the [PartConv](http://doc.sccode.org/Classes/PartConv.html) UGen by Nick Collins instead!

**Comment by sonoro1234** [comment]
the recomendation was from Nick Collins in the list, but long time ago
